// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";
import * as dotenv from "dotenv";
import * as path from "path";

// Explicitly load the .env file from the monorepo root
dotenv.config({ path: path.resolve(process.cwd(), "../../.env") });
// Fallback to local .env if it exists in the database package
dotenv.config();


export default defineConfig({
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "./prisma/migrations",
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
